[functions.generate-diet]
enabled = true
verify_jwt = false
entrypoint = "./functions/generate-diet/index.ts"

[functions.generate-workout]
enabled = true
verify_jwt = false
entrypoint = "./functions/generate-workout/index.ts"